# Generated by Django 4.2.7 on 2023-11-22 12:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0002_delete_generatervideimage_delete_userinfo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneraterVideImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('generater_video_image', models.ImageField(default='images/default.pdf', upload_to='images/')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('video_id', models.CharField(max_length=200)),
                ('download_link', models.URLField(unique=True)),
                ('time_created', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user_email', models.EmailField(max_length=200)),
                ('video_count', models.IntegerField(default=0)),
                ('subscription_status', models.CharField(choices=[('free', 'free'), ('Standard', 'Standard'), ('Advanced', 'Advanced'), ('Premium', 'Premium')], max_length=100)),
                ('user_video', models.ManyToManyField(blank=True, to='User.videos')),
            ],
        ),
    ]
