# Generated by Django 4.2.7 on 2023-11-24 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_videos_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='video_count',
        ),
    ]
