# Generated by Django 4.2.7 on 2023-11-24 09:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_remove_userinfo_video_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatervideimage',
            name='status',
            field=models.CharField(choices=[('inactive', 'inactive'), ('acive', 'active')], default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generatervideimage',
            name='title',
            field=models.CharField(default='My_Image', max_length=200),
        ),
    ]
